esphome:
  name: kandey
  friendly_name: Konditioner

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:
  level: VERBOSE
# Enable Home Assistant API

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kandey Fallback Hotspot"
    password: ""

substitutions:
  device_name: tclac
  humanly_name: TCL Air Conditioner
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  recovery_pass: ssid_pass
  ota_pass: your_ota_pass
  api_key: your_api_key
  uart_rx: GPIO3
  uart_tx: GPIO1
  receive_led: GPIO2
  transmit_led: GPIO2

packages:
  remote_package:
    url: https://github.com/I-am-nightingale/tclac.git
    ref: master
    files:
      - packages/core.yaml
    refresh: 30s
